### ISSUE TITLE
What is the result of confident learning without sub1/2 ?

### ISSUE THREAD

**Issue by dh23333** [502463708/Confident_Learning_for_Noisy-labeled_Medical_Image_Segmentation#2]
I didn't divide it into sub1/2 when processing data, but it didn't work well. Is it the reason for the data processing? If it is not divided into sub1/2, what should the result of this algorithm?

**Comment by 502463708** [comment]
I didn't investigate the case where sub1/2 is kept as a whole. But I guess the performance in that case could be unideal.  Because CNNs are proved to have the capacity of fitting random noise, they tend to overfit the label noises when sub1/2 is not divided.

**Comment by huanghjA** [comment]
Hello, does this means I should train a teacher model based on sub1 instead of all?

**Comment by 502463708** [comment]
Based on sub1 and sub2 respectively, you will have two models (model_1 and model_2). Make cross-evaluation using model_1 for sub_2 and model_2 for sub_1, you will have the noise identification results.

**Comment by huanghjA** [comment]
Thanks a lot! I have got the recall 70.49% and precision 62.73% when class is clavicle, alpha is 0.3, and beta is 5.
